#+TITLE: Vagrant ReadMe

* Introduction

Not quite working version ..

* Basic Commands

There isn't much required to get a basic virtualbox system up and
running:

- *mkdir vagrant_test*
- *cd vagrant_test*
- *vagrant init "machine"*
  - edit the /Vagrantfile/
- *vagrant up*

The /Vagrantfile/ contains the details of the system which is required.

* Example Vagrant Machine

On the command line:

- *git clone https://github.com/paulmassey42/VagrantUnifiedViews2.x.git*
- *cd VagrantUnifiedViews2.x*
- *vagrant plugin install vagrant-vbguest*
- *vagrant up*
  Possibly select you network interface connection point
  This will take a *long* time the first time

Then to make sure the GUI interface is usable from the virtual machine

- *vagrant halt*
- *vagrant up*

Then it should be possible to use the virtual machine
 
- Login password: /vagrant/

- Select the iceweasel web-browser

- access http://localhost:8080/unifiedviews  (Not working)

  Login account  : /admin/
  Login password : /test/

- Unifiedviews functions should then be accessible.

* Notes:
- Depending on the underlying system, it seems that the network
  connections settings sometimes cause problems (*halt*, wait a while
  and *up* again, normally clears the problem).
- some freezes have been observed.

